### ISSUE TITLE
Add support for older CMake versions ( e.g. 3.8.2 )

### ISSUE THREAD

**Issue by caxkal** [nlohmann/crow#30]
Sometimes there is need to use old CMake ( because of legacy, or required system ).
Please add support for older version of CMake.

**Comment by nlohmann** [comment]
Do you know which versions are making problems with your older CMake version? Unfortunately, I am not aware of tooling to see which line in the `CMakeLists.txt` causes which minimal CMake version.

**Comment by caxkal** [comment]
I am trying to use cmake 3.8.2. 
Problematic lines are:

cmake_host_system_information(RESULT NLOHMANN_CROW_OS_RELEASE QUERY OS_RELEASE)
cmake_host_system_information(RESULT NLOHMANN_CROW_OS_VERSION QUERY OS_VERSION)

**Comment by nlohmann** [comment]
Both `OS_RELEASE` and `OS_VERSION` were introduced in CMake 3.10 and are currently required by Crow. As Crow is still in early development, support for earlier CMake versions is currently not on the roadmap.

**Comment by nlohmann** [comment]
Fixed with upcoming Crow 0.0.6.
