### ISSUE TITLE
Is this repository abandoned? 

### ISSUE THREAD

**Issue by goranbrkic** [nlohmann/crow#45]
While it is normal for a repository to be left out when main developer focuses on something else, it would be helpful if we could at least flag it as such.

There are at time of this writing 10 other issues and 4 pull requests older than five months.

**Comment by nlohmann** [comment]
Right now, I do only have limited time in working on this project. I started to use Crow in a production project and hope to be able to bring back some of the changes we did there back to this repository.

**Comment by goranbrkic** [comment]
Is there any way that you could setup contributing guidelines so other people could help.
Even just responding to issues and pull requests could be immensely helpful and would help keep this project alive.

**Comment by nlohmann** [comment]
Well, for the PRs, a green CI would be helpful... I will try to prioritize Crow more, but I cannot promise anything at the moment.

**Comment by goranbrkic** [comment]
Closing this issue, as this repository is still supported.
