### ISSUE TITLE
Plans to tag and release "update" branch (2.4.0)?

### ISSUE THREAD

**Issue by justinfx** [nlohmann/crow#51]
Hi @nlohmann . Thanks for the great looking project! I started swapping in this client instead of sentry_native because of the proper support for hubs instead of application main-style global clients. At first I started by forking and merging the pending patches from the issues into master. And then I found that the "update" branch has everything already done, so I am now using that branch.

Are there plans to merge, tag, and release the "update" branch as 2.4.0? I would like to start using this in my internal work project and get a proper internal deploy, but it would be great if it were properly tagged. Are you still maintaining this project? Otherwise my other option is to use my fork to  tag the "update" branch as something like "2.4.0-alpha.0" so that we can internally deploy it.

**Comment by nlohmann** [comment]
Hey! I am currently not actively working on Crow in this repository. At work, we forked the repository and made a lot of changes, but I am not sure whether I can bring them back to this repo - but I will check.

However, making that branch a pre-release should not be a problem. Let me see if I can do it right away.

**Comment by nlohmann** [comment]
Done: https://github.com/nlohmann/crow/releases/tag/v2.4.0

**Comment by nlohmann** [comment]
PS: 🙏 Thanks for your donation!

**Comment by justinfx** [comment]
Works for me, thanks! Will keep an eye out for whether you are able to merge your internal work, and/or if you merge into master.
